### ISSUE TITLE
tensorflow.python.framework.errors_impl.PermissionDeniedError: resnet50; Permission denied

### ISSUE THREAD

**Issue by Jeremy-lf** [arashno/tensorflow_multigpu_imagenet#20]
when i run python run.py train  --path_prefix /home/ccf_disk/dataset/imagenet --train_info train.txt  --num_epochs 50 ,it happened above, what's wrong?

**Comment by arashno** [comment]
I have no idea.
Could you please post the complete stack trace?

**Comment by Jeremy-lf** [comment]
hi, thanks  for your reply . the above issue has been solved! Now i design a new network, and training it  with imagenet  dataset,  but i have encounter a new problem :  
ValueError: No variables  to optimize   what's wrong?

**Comment by Jeremy-lf** [comment]
like this :

**Comment by Jeremy-lf** [comment]
Filling queue with 2000 images before starting to train. This may take some times.
Traceback (most recent call last):
  File "run.py", line 386, in <module>
    main()
  File "run.py", line 358, in main
    do_train(sess, args)
  File "run.py", line 78, in do_train
    train_ops = dnn_model.train_ops()
  File "/home/ccf_disk/lvfeng/lvfeng/tensorflow_multigpu_imagenet-master/architectures/model.py", line 183, in train_ops
    grads, last_grads, batchnorm_updates, cross_entropy_mean, top1acc, topnacc = self.multigpu_grads()
  File "/home/ccf_disk/lvfeng/lvfeng/tensorflow_multigpu_imagenet-master/architectures/model.py", line 157, in multigpu_grads
    grads, last_grads, batchnorm_updates, cross_entropy_mean, top1acc, topnacc = self.get_grads('/gpu:%d' % i)
  File "/home/ccf_disk/lvfeng/lvfeng/tensorflow_multigpu_imagenet-master/architectures/model.py", line 132, in get_grads
    last_grads = self.optimizer.compute_gradients(total_loss,var_list= tf.get_collection(SAVE_VARIABLES, scope='output'))
  File "/home/aicer/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 505, in compute_gradients
    raise ValueError("No variables to optimize.")
ValueError: No variables to optimize.
