### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by liuzhisheng1226** [arashno/tensorflow_multigpu_imagenet#6]
Namespace(LR_steps=[19, 30, 44, 53], LR_values=[0.01, 0.005, 0.001, 0.0005, 0.0001], WD_steps=[30], WD_values=[0.0005, 0.0], architecture='resnet', batch_size=128, chunked_batch_size=128, crop_size=[224, 224], data_info='train.txt', delimiter=' ', depth=50, load_size=[256, 256], log_debug_info=False, log_device_placement=False, log_dir='resnet_Run-14-03-2018_16-14-32', max_to_keep=5, num_batches=10010, num_channels=3, num_classes=1000, num_epochs=55, num_gpus=1, num_samples=1281166, num_threads=20, path_prefix='./', retrain_from=None, run_name='Run-14-03-2018_16-14-32', shuffle=True, snapshot_prefix='snapshot', top_n=5, transfer_mode=[0])
Saving everything in resnet_Run-14-03-2018_16-14-32
Filling queue with 2000 images before starting to train. This may take some times.
Traceback (most recent call last):
  File "train.py", line 350, in <module>
    main()
  File "train.py", line 346, in main
    train(args)
  File "train.py", line 130, in train
    logits = arch.get_model(images, wd, is_training, args)
  File "/home/liuzhisheng/.workspace/test/.workspace/tensorflow_multigpu_imagenet/arch.py", line 12, in get_model
    return architectures.resnet.inference(inputs, args.depth, args.num_classes, wd, is_training, transferMode)
  File "/home/liuzhisheng/.workspace/test/.workspace/tensorflow_multigpu_imagenet/architectures/resnet.py", line 24, in inference
    return getModel(x, num_output, wd, is_training, num_blocks= num_blocks, bottleneck= bottleneck, transfer_mode= transfer_mode)
  File "/home/liuzhisheng/.workspace/test/.workspace/tensorflow_multigpu_imagenet/architectures/resnet.py", line 33, in getModel
    x = common.batchNormalization(x, is_training= is_training)
  File "/home/liuzhisheng/.workspace/test/.workspace/tensorflow_multigpu_imagenet/architectures/common.py", line 39, in batchNormalization
    initializer= tf.zeros_initializer)
  File "/home/liuzhisheng/.workspace/test/.workspace/tensorflow_multigpu_imagenet/architectures/common.py", line 26, in _get_variable
    trainable= trainable)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 684, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 226, in __init__
    expected_shape=expected_shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 303, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 673, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: __init__() got multiple values for keyword argument 'dtype'

**Comment by arashno** [comment]
Does not seem like a bug.
When does it happen? 
What arguments have you used?

**Comment by liuzhisheng1226** [comment]
I don't use any arguments....

**Comment by liuzhisheng1226** [comment]
when I use python train.py --path_prefix /project/datasets/imagenet/train/,it throws the same problem.

**Comment by arashno** [comment]
The problem is not with my code.
I guess it is a version incompatibility.
What version of tensorflow are you using?

**Comment by liuzhisheng1226** [comment]
'1.0.0'

**Comment by arashno** [comment]
Yes, it is a version incompatibility.
The solution suggested here may solve your problem:
https://github.com/tensorflow/tensorflow/issues/5742

Or you can update your tensorflow.
